version: 1
disable_existing_loggers: false
formatters:
  pytroll:
    format: '[%(asctime)s %(levelname)-8s %(name)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: pytroll
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console, monitor]
